/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aps4;

import java.io.IOException;
import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class Servidor extends javax.swing.JFrame {
    static int posicaoNumSorteado = 0;
    static boolean bingoComecou = false;
    ServerSocket serverSocket;
    int idx;
    Thread t;
    Thread t2;

    DefaultTableModel model;
    private ArrayList<Conexao> clientesConectados = new ArrayList<>();
    static int[] numSorteados = new int[76];

    /**
     * Creates new form Servidor
     */
    public Servidor() {
        initComponents();
        model = (DefaultTableModel) jTableClientes.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        serverTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextPorta = new javax.swing.JTextField();
        jButtonLigar = new javax.swing.JButton();
        EnviarNumeros = new javax.swing.JButton();
        jButtonIniciarBingo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serverTextArea.setColumns(20);
        serverTextArea.setRows(5);
        jScrollPane1.setViewportView(serverTextArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Servidor:");

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IP", "Porta", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableClientes);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Porta:");

        jTextPorta.setText("20000");
        jTextPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPortaActionPerformed(evt);
            }
        });

        jButtonLigar.setText("Ligar");
        jButtonLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLigarActionPerformed(evt);
            }
        });

        EnviarNumeros.setText("Enviar todos os números");
        EnviarNumeros.setActionCommand("EnviarNumeros ");
        EnviarNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarTodosNumeros(evt);
            }
        });

        jButtonIniciarBingo.setText("Iniciar Bingo");
        jButtonIniciarBingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarBingoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonIniciarBingo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EnviarNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLigar)
                        .addComponent(jButtonIniciarBingo)
                        .addComponent(EnviarNumeros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPortaActionPerformed

    private void jButtonLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLigarActionPerformed

        jButtonLigar.setEnabled(false);

        t = new Thread() {

            @Override

            public void run() {
                try {
                    serverSocket = new ServerSocket(Integer.parseInt(jTextPorta.getText()));
                    serverTextArea.setText("Server inicado em " + Integer.parseInt(jTextPorta.getText()) + "\n");
                    idx = 0;
                    while (true) {
                        Socket clientSocket;
                        clientSocket = serverSocket.accept();

                        System.out.println(idx);
                        Conexao conexao = new Conexao(clientSocket, idx, serverTextArea, model, clientesConectados, numSorteados);
                        conexao.start();
                        clientesConectados.add(conexao);
                        idx++;

                        if (false) {
                            break;
                        }
                    }
                    serverSocket.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        };

        t.start();
    }//GEN-LAST:event_jButtonLigarActionPerformed

    private void EnviarTodosNumeros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarTodosNumeros
        bingoComecou = true;
        int rand;

        jButtonIniciarBingo.setEnabled(false);
        EnviarNumeros.setEnabled(false);

        for (int i = 0; i < 75; i++) {
            rand = new Random().nextInt(75) + 1;

            if (!numRepetido(rand)) {
                numSorteados[i] = rand;
            } else {
                i--;
            }
        }

        for (int i = 0; i < 75; i++) {
            serverTextArea.setText(serverTextArea.getText() + "Número Sorteado: " + numSorteados[i] + "\n");
            for (Conexao c : clientesConectados) {
                c.enviarMensagem("10#" + numSorteados[i]);
                posicaoNumSorteado = i;
            }
        }
    }//GEN-LAST:event_EnviarTodosNumeros

    private void jButtonIniciarBingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarBingoActionPerformed
        bingoComecou = true;

        jButtonIniciarBingo.setEnabled(false);
        EnviarNumeros.setEnabled(false);

        t2 = new Thread() {
            int rand;

            @Override

            public void run() {
                for (int i = 0; i < 75; i++) {
                    rand = new Random().nextInt(75) + 1;

                    if (!numRepetido(rand)) {
                        numSorteados[i] = rand;
                    } else {
                        i--;
                    }
                }

                for (int i = 0; i < 75; i++) {
                    serverTextArea.setText(serverTextArea.getText() + "Número Sorteado: " + numSorteados[i] + "\n");
                    for (Conexao c : clientesConectados) {
                        c.enviarMensagem("10#" + numSorteados[i]);
                        posicaoNumSorteado = i;
                    }
                    try {
                        t2.sleep(15000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Servidor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };

        t2.start();
    }//GEN-LAST:event_jButtonIniciarBingoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarNumeros;
    private javax.swing.JButton jButtonIniciarBingo;
    private javax.swing.JButton jButtonLigar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextPorta;
    private javax.swing.JTextArea serverTextArea;
    // End of variables declaration//GEN-END:variables

    private boolean numRepetido(int num) {
        for (int i = 0; i < 76; i++) {
            if (numSorteados[i] == num) {
                return true;
            }
        }
        return false;
    }
}
